# Generated by Django 4.0 on 2021-12-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaxp', '0002_rename_agility_hero_agility_initial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='agility_initial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='intelligence_initial',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hero',
            name='strength_initial',
            field=models.IntegerField(default=0),
        ),
    ]
