# Generated by Django 4.0 on 2021-12-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotaxp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='agility',
            new_name='agility_initial',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='intelligence',
            new_name='intelligence_initial',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='strength',
            new_name='strength_initial',
        ),
        migrations.AddField(
            model_name='hero',
            name='agility_gain',
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AddField(
            model_name='hero',
            name='intelligence_gain',
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AddField(
            model_name='hero',
            name='strength_gain',
            field=models.DecimalField(
                decimal_places=1, default=0, max_digits=4
            ),
        ),
        migrations.AlterField(
            model_name='hero',
            name='main_attribute',
            field=models.CharField(
                choices=[
                    ('AGI', 'Agility'),
                    ('INT', 'Intelligence'),
                    ('STR', 'Strength'),
                ],
                max_length=3,
            ),
        ),
    ]
