# Generated by Django 4.0 on 2021-12-08 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotaxp', '0003_alter_hero_agility_initial_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='agility_gain',
            new_name='gain_agi',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='intelligence_gain',
            new_name='gain_int',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='strength_gain',
            new_name='gain_str',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='agility_initial',
            new_name='init_agi',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='intelligence_initial',
            new_name='init_int',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='strength_initial',
            new_name='init_str',
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='main_attribute',
            new_name='main_attr',
        ),
        migrations.CreateModel(
            name='HeroLife',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'level',
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MaxValueValidator(30)
                        ],
                    ),
                ),
                (
                    'hero',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='dotaxp.hero',
                    ),
                ),
            ],
        ),
    ]
