# Generated by Django 4.0 on 2021-12-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotaxp', '0004_rename_agility_gain_hero_gain_agi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'heroes'},
        ),
        migrations.AlterModelOptions(
            name='herolife',
            options={'verbose_name': 'hero lives'},
        ),
    ]
