# Generated by Django 4.0 on 2021-12-08 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotaxp', '0006_alter_hero_options_alter_herolife_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroLife',
        ),
    ]
